server:
  port: 8080

spring:
  application:
    name: pizzeria-lite

  datasource:
    url: jdbc:postgresql://db:5432/pizzeria_db
    username: pizzeria_user
    password: pizzeria_pass123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: always

# API key de un proveedor de notificaciones ficticio, hardcodeada en el archivo de config
notification:
  provider-url: https://api.fake-sms-provider.com/v1/send
  api-key: sk_test_51H8xJ2KfakeApiKey0001112223334445556667778889990
